baseURL = 'https://test.blatbastards.com/'
languageCode = 'en-us'
title = 'Test Blat Bastards'
theme = "hugo-theme-cleanwhite"
#  theme = "ananke"

[params]
  # Load our extra CSS
  custom_css = ["css/custom.css"]

[taxonomies]
  tag = "tags"
  category = "categories"